"""
metacore.server.routes_brain — Brain status and daily report endpoints.

Serves the daily brain report generated by learner.py cognition_tick.
Provides a window into the AGI's self-awareness and ongoing activity.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import List

from fastapi import APIRouter, Query

router = APIRouter(tags=["brain"])

_REPORTS_DIR = Path.home() / ".aelvoxim" / "reports" / "daily"

from .routes import _verify_key, _require_admin
from fastapi import Depends


import logging
_log = logging.getLogger("aelvoxim.server.routes_brain")

@router.get("/brain/report")
async def get_brain_report(date: str = Query("", description="Date in YYYY-MM-DD format, defaults to today"),
                           _user: dict = Depends(_verify_key)):
    """Get the daily brain report for a specific date (default: today)."""
    from .. import _EDITION
    if _EDITION == "community":
        return {"date": date or "today", "report": None, "message": "Brain reports are a Pro feature"}

    report_date = date or datetime.now().strftime("%Y-%m-%d")
    report_path = _REPORTS_DIR / f"{report_date}.md"

    if not report_path.exists():
        return {
            "date": report_date,
            "report": None,
            "message": "No report for this date",
        }

    content = report_path.read_text(encoding="utf-8")
    return {"date": report_date, "report": content}


@router.get("/brain/reports")
async def list_brain_reports(limit: int = Query(7, description="Max reports to list"),
                             _user: dict = Depends(_verify_key)):
    """List available daily brain report dates, newest first."""
    if not _REPORTS_DIR.exists():
        return {"reports": []}

    files = sorted(_REPORTS_DIR.glob("*.md"), reverse=True)[:limit]
    return {"reports": [f.stem for f in files]}


@router.get("/brain/status")
async def get_brain_status(_user: dict = Depends(_verify_key)):
    """Return a compact JSON status snapshot of the brain."""
    try:
        from ..core.selfmodel import SelfModel

        sm = SelfModel()
        caps = sm._capabilities
        bc = caps.get("belief_health")
        grade_result = sm.overall_grade()
        grade_label = grade_result.get("grade", "N/A") if isinstance(grade_result, dict) else str(grade_result)

        # Try to count active directions from learner
        active_dirs = 0
        from ..learn.learner import get_learner
        try:
            learner = get_learner()
            active_dirs = sum(
                1 for d in (learner._directions or {}).values()
                if d.status == "active"
            )
        except Exception:
            _log.exception("routes_brain error")

        return {
            "grade": grade_label,
            "belief_health": round(bc.success_rate, 2) if bc else None,
            "active_directions": active_dirs,
            "capabilities": {
                name: round(cap.success_rate, 2)
                for name, cap in (caps or {}).items()
            },
        }
    except Exception:
        return {"error": "Status unavailable"}
